#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-plotly
Version  : 4.9.3
Release  : 39
URL      : https://cran.r-project.org/src/contrib/plotly_4.9.3.tar.gz
Source0  : https://cran.r-project.org/src/contrib/plotly_4.9.3.tar.gz
Summary  : Create Interactive Web Graphics via 'plotly.js'
Group    : Development/Tools
License  : ISC MIT
Requires: R-RColorBrewer
Requires: R-base64enc
Requires: R-crosstalk
Requires: R-data.table
Requires: R-digest
Requires: R-dplyr
Requires: R-ggplot2
Requires: R-htmltools
Requires: R-htmlwidgets
Requires: R-httr
Requires: R-jsonlite
Requires: R-lazyeval
Requires: R-magrittr
Requires: R-promises
Requires: R-purrr
Requires: R-rlang
Requires: R-scales
Requires: R-tibble
Requires: R-tidyr
Requires: R-vctrs
Requires: R-viridisLite
BuildRequires : R-RColorBrewer
BuildRequires : R-base64enc
BuildRequires : R-crosstalk
BuildRequires : R-data.table
BuildRequires : R-digest
BuildRequires : R-dplyr
BuildRequires : R-ggplot2
BuildRequires : R-htmltools
BuildRequires : R-htmlwidgets
BuildRequires : R-httr
BuildRequires : R-jsonlite
BuildRequires : R-lazyeval
BuildRequires : R-magrittr
BuildRequires : R-promises
BuildRequires : R-purrr
BuildRequires : R-rlang
BuildRequires : R-scales
BuildRequires : R-tibble
BuildRequires : R-tidyr
BuildRequires : R-vctrs
BuildRequires : R-viridisLite
BuildRequires : buildreq-R

%description
<img src="man/figures/plotly.png" width="200" />
[![Build
Status](https://travis-ci.org/ropensci/plotly.png?branch=master)](https://travis-ci.org/ropensci/plotly)
[![CRAN
Status](https://www.r-pkg.org/badges/version/plotly)](https://cran.r-project.org/package=plotly)
[![CRAN
Downloads](https://cranlogs.r-pkg.org/badges/grand-total/plotly)](https://www.rpackages.io/package/plotly)
[![monthly](https://cranlogs.r-pkg.org/badges/plotly)](https://www.rpackages.io/package/plotly)

%prep
%setup -q -c -n plotly
cd %{_builddir}/plotly

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1610302550

%install
export SOURCE_DATE_EPOCH=1610302550
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library plotly
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library plotly
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library plotly
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc plotly || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/plotly/CITATION
/usr/lib64/R/library/plotly/DESCRIPTION
/usr/lib64/R/library/plotly/INDEX
/usr/lib64/R/library/plotly/LICENSE
/usr/lib64/R/library/plotly/Meta/Rd.rds
/usr/lib64/R/library/plotly/Meta/data.rds
/usr/lib64/R/library/plotly/Meta/demo.rds
/usr/lib64/R/library/plotly/Meta/features.rds
/usr/lib64/R/library/plotly/Meta/hsearch.rds
/usr/lib64/R/library/plotly/Meta/links.rds
/usr/lib64/R/library/plotly/Meta/nsInfo.rds
/usr/lib64/R/library/plotly/Meta/package.rds
/usr/lib64/R/library/plotly/NAMESPACE
/usr/lib64/R/library/plotly/NEWS.md
/usr/lib64/R/library/plotly/R/plotly
/usr/lib64/R/library/plotly/R/plotly.rdb
/usr/lib64/R/library/plotly/R/plotly.rdx
/usr/lib64/R/library/plotly/R/sysdata.rdb
/usr/lib64/R/library/plotly/R/sysdata.rdx
/usr/lib64/R/library/plotly/data/Rdata.rdb
/usr/lib64/R/library/plotly/data/Rdata.rds
/usr/lib64/R/library/plotly/data/Rdata.rdx
/usr/lib64/R/library/plotly/demo/animation-tour-USArrests.R
/usr/lib64/R/library/plotly/demo/animation-tour-basic.R
/usr/lib64/R/library/plotly/demo/crosstalk-filter-dynamic-axis.R
/usr/lib64/R/library/plotly/demo/crosstalk-filter-lines.R
/usr/lib64/R/library/plotly/demo/crosstalk-highlight-binned-target-a.R
/usr/lib64/R/library/plotly/demo/crosstalk-highlight-binned-target-b.R
/usr/lib64/R/library/plotly/demo/crosstalk-highlight-binned-target-c.R
/usr/lib64/R/library/plotly/demo/crosstalk-highlight-epl-2.R
/usr/lib64/R/library/plotly/demo/crosstalk-highlight-epl.R
/usr/lib64/R/library/plotly/demo/crosstalk-highlight-ggpairs.R
/usr/lib64/R/library/plotly/demo/crosstalk-highlight-ggplotly.R
/usr/lib64/R/library/plotly/demo/crosstalk-highlight-intro.R
/usr/lib64/R/library/plotly/demo/crosstalk-highlight-leaflet.R
/usr/lib64/R/library/plotly/demo/crosstalk-highlight-pipeline.R
/usr/lib64/R/library/plotly/demo/crosstalk-highlight-subplot.R
/usr/lib64/R/library/plotly/demo/custom-javascript.R
/usr/lib64/R/library/plotly/demo/rotate.R
/usr/lib64/R/library/plotly/demo/sf-dt.R
/usr/lib64/R/library/plotly/demo/sf-geo.R
/usr/lib64/R/library/plotly/demo/sf-ggplot2.R
/usr/lib64/R/library/plotly/demo/sf-mapbox-data.R
/usr/lib64/R/library/plotly/demo/sf-mapbox-layout.R
/usr/lib64/R/library/plotly/demo/sf-mapbox-style.R
/usr/lib64/R/library/plotly/demo/sf-plotly-3D-globe.R
/usr/lib64/R/library/plotly/demo/sf-plotly-storms.R
/usr/lib64/R/library/plotly/demo/ternary.R
/usr/lib64/R/library/plotly/docker/Dockerfile.vtest
/usr/lib64/R/library/plotly/docker/README.md
/usr/lib64/R/library/plotly/docs.R
/usr/lib64/R/library/plotly/examples/rmd/MathJax/index.Rmd
/usr/lib64/R/library/plotly/examples/rmd/flexdashboard/index.Rmd
/usr/lib64/R/library/plotly/examples/rmd/onRenderHover/index.Rmd
/usr/lib64/R/library/plotly/examples/rmd/printing/index.Rmd
/usr/lib64/R/library/plotly/examples/shiny/DT/app.R
/usr/lib64/R/library/plotly/examples/shiny/Diamonds/server.R
/usr/lib64/R/library/plotly/examples/shiny/Diamonds/ui.R
/usr/lib64/R/library/plotly/examples/shiny/MathJax/app.R
/usr/lib64/R/library/plotly/examples/shiny/Movies/server.R
/usr/lib64/R/library/plotly/examples/shiny/Movies/ui.R
/usr/lib64/R/library/plotly/examples/shiny/UN_Advanced/Data/UN_IdealPoints.csv
/usr/lib64/R/library/plotly/examples/shiny/UN_Advanced/global.R
/usr/lib64/R/library/plotly/examples/shiny/UN_Advanced/server.R
/usr/lib64/R/library/plotly/examples/shiny/UN_Advanced/ui.R
/usr/lib64/R/library/plotly/examples/shiny/UN_Simple/Data/UN_IdealPoints.csv
/usr/lib64/R/library/plotly/examples/shiny/UN_Simple/global.R
/usr/lib64/R/library/plotly/examples/shiny/UN_Simple/server.R
/usr/lib64/R/library/plotly/examples/shiny/UN_Simple/ui.R
/usr/lib64/R/library/plotly/examples/shiny/async/app.R
/usr/lib64/R/library/plotly/examples/shiny/basic/DESCRIPTION
/usr/lib64/R/library/plotly/examples/shiny/crossfilter/app.R
/usr/lib64/R/library/plotly/examples/shiny/crossfilter_compare/app.R
/usr/lib64/R/library/plotly/examples/shiny/crossfilter_kde/app.R
/usr/lib64/R/library/plotly/examples/shiny/crossfilter_scatter/app.R
/usr/lib64/R/library/plotly/examples/shiny/drag_brush/app.R
/usr/lib64/R/library/plotly/examples/shiny/drag_lines/app.R
/usr/lib64/R/library/plotly/examples/shiny/drag_markers/app.R
/usr/lib64/R/library/plotly/examples/shiny/drill_down/app.R
/usr/lib64/R/library/plotly/examples/shiny/event_data/DESCRIPTION
/usr/lib64/R/library/plotly/examples/shiny/event_data/app.R
/usr/lib64/R/library/plotly/examples/shiny/event_data/tests/shinytest/mytest-expected/001.json
/usr/lib64/R/library/plotly/examples/shiny/event_data/tests/shinytest/mytest-expected/001.png
/usr/lib64/R/library/plotly/examples/shiny/event_data/tests/shinytest/mytest-expected/002.json
/usr/lib64/R/library/plotly/examples/shiny/event_data/tests/shinytest/mytest-expected/002.png
/usr/lib64/R/library/plotly/examples/shiny/event_data/tests/shinytest/mytest-expected/003.json
/usr/lib64/R/library/plotly/examples/shiny/event_data/tests/shinytest/mytest-expected/003.png
/usr/lib64/R/library/plotly/examples/shiny/event_data/tests/shinytest/mytest-expected/004.json
/usr/lib64/R/library/plotly/examples/shiny/event_data/tests/shinytest/mytest-expected/004.png
/usr/lib64/R/library/plotly/examples/shiny/event_data/tests/shinytest/mytest.R
/usr/lib64/R/library/plotly/examples/shiny/event_data_3D/app.R
/usr/lib64/R/library/plotly/examples/shiny/event_data_annotation/app.R
/usr/lib64/R/library/plotly/examples/shiny/event_data_click/DESCRIPTION
/usr/lib64/R/library/plotly/examples/shiny/event_data_click/app.R
/usr/lib64/R/library/plotly/examples/shiny/event_data_click_map/app.R
/usr/lib64/R/library/plotly/examples/shiny/event_data_legends/app.R
/usr/lib64/R/library/plotly/examples/shiny/event_data_modules/app.R
/usr/lib64/R/library/plotly/examples/shiny/event_data_parcoords/app.R
/usr/lib64/R/library/plotly/examples/shiny/event_data_persist/app.R
/usr/lib64/R/library/plotly/examples/shiny/event_data_select/app.R
/usr/lib64/R/library/plotly/examples/shiny/event_priority/app.R
/usr/lib64/R/library/plotly/examples/shiny/ggplotly_sizing/app.R
/usr/lib64/R/library/plotly/examples/shiny/lmGadget/app.R
/usr/lib64/R/library/plotly/examples/shiny/proxy_mapbox/app.R
/usr/lib64/R/library/plotly/examples/shiny/proxy_relayout/app.R
/usr/lib64/R/library/plotly/examples/shiny/proxy_restyle_canada/app.R
/usr/lib64/R/library/plotly/examples/shiny/proxy_restyle_economics/app.R
/usr/lib64/R/library/plotly/examples/shiny/stream/app.R
/usr/lib64/R/library/plotly/help/AnIndex
/usr/lib64/R/library/plotly/help/aliases.rds
/usr/lib64/R/library/plotly/help/figures/plotly.png
/usr/lib64/R/library/plotly/help/figures/plotly.svg
/usr/lib64/R/library/plotly/help/paths.rds
/usr/lib64/R/library/plotly/help/plotly.rdb
/usr/lib64/R/library/plotly/help/plotly.rdx
/usr/lib64/R/library/plotly/html/00Index.html
/usr/lib64/R/library/plotly/html/R.css
/usr/lib64/R/library/plotly/htmlwidgets/lib/colourpicker/LICENSE
/usr/lib64/R/library/plotly/htmlwidgets/lib/colourpicker/colourpicker.min.css
/usr/lib64/R/library/plotly/htmlwidgets/lib/colourpicker/colourpicker.min.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/mathjax/cdn.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/LICENSE
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/af.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/am.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/ar-dz.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/ar-eg.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/ar.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/az.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/bg.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/bs.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/ca.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/cs.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/cy.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/da.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/de-ch.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/de.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/el.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/eo.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/es-ar.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/es-pe.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/es.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/et.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/eu.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/fa.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/fi.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/fo.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/fr-ch.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/fr.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/gl.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/gu.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/he.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/hi-in.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/hr.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/hu.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/hy.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/id.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/is.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/it.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/ja.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/ka.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/km.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/ko.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/lt.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/lv.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/me-me.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/me.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/mk.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/ml.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/ms.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/mt.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/nl-be.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/nl.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/no.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/pa.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/pl.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/pt-br.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/pt-pt.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/rm.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/ro.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/ru.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/sk.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/sl.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/sq.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/sr-sr.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/sr.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/sv.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/sw.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/ta.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/th.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/tr.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/tt.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/uk.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/ur.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/vi.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/zh-cn.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/zh-hk.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/locales/zh-tw.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/plotly-htmlwidgets.css
/usr/lib64/R/library/plotly/htmlwidgets/lib/plotlyjs/plotly-latest.min.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/selectize/selectize.bootstrap3.css
/usr/lib64/R/library/plotly/htmlwidgets/lib/selectize/selectize.min.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/setprototypeof/LICENSE
/usr/lib64/R/library/plotly/htmlwidgets/lib/setprototypeof/setprototypeof.js
/usr/lib64/R/library/plotly/htmlwidgets/lib/typedarray/LICENSE
/usr/lib64/R/library/plotly/htmlwidgets/lib/typedarray/typedarray.min.js
/usr/lib64/R/library/plotly/htmlwidgets/plotly.js
/usr/lib64/R/library/plotly/htmlwidgets/plotly.yaml
/usr/lib64/R/library/plotly/plotlyjs.R
/usr/lib64/R/library/plotly/stars.R
/usr/lib64/R/library/plotly/tests/figs/abline/cookbook-axes-multiple-abline.svg
/usr/lib64/R/library/plotly/tests/figs/abline/cookbook-axes-single-abline.svg
/usr/lib64/R/library/plotly/tests/figs/area/area-area-fillcolor.svg
/usr/lib64/R/library/plotly/tests/figs/area/area-simple.svg
/usr/lib64/R/library/plotly/tests/figs/area/area-traces-order.svg
/usr/lib64/R/library/plotly/tests/figs/axes/ticktext-linebreaks-no-linebreaks.svg
/usr/lib64/R/library/plotly/tests/figs/axes/ticktext-linebreaks-one-cat.svg
/usr/lib64/R/library/plotly/tests/figs/axes/ticktext-linebreaks.svg
/usr/lib64/R/library/plotly/tests/figs/bar/bar-aes-colour-guides-fill-false.svg
/usr/lib64/R/library/plotly/tests/figs/bar/bar-aes-fill-guides-color-none.svg
/usr/lib64/R/library/plotly/tests/figs/bar/bar-black-outline.svg
/usr/lib64/R/library/plotly/tests/figs/bar/bar-category-names.svg
/usr/lib64/R/library/plotly/tests/figs/bar/bar-color.svg
/usr/lib64/R/library/plotly/tests/figs/bar/bar-coord-flip.svg
/usr/lib64/R/library/plotly/tests/figs/bar/bar-dates.svg
/usr/lib64/R/library/plotly/tests/figs/bar/bar-dodge.svg
/usr/lib64/R/library/plotly/tests/figs/bar/bar-identity.svg
/usr/lib64/R/library/plotly/tests/figs/bar/bar-nocolor.svg
/usr/lib64/R/library/plotly/tests/figs/bar/bar-position-fill.svg
/usr/lib64/R/library/plotly/tests/figs/bar/bar-position-stack.svg
/usr/lib64/R/library/plotly/tests/figs/bar/bar-stack.svg
/usr/lib64/R/library/plotly/tests/figs/boxplot/boxplot-datetime.svg
/usr/lib64/R/library/plotly/tests/figs/boxplot/boxplot-fillcolor.svg
/usr/lib64/R/library/plotly/tests/figs/boxplot/boxplot-legends-for-fill.svg
/usr/lib64/R/library/plotly/tests/figs/boxplot/boxplot.svg
/usr/lib64/R/library/plotly/tests/figs/colorbar/plotly-colorbar-expand.svg
/usr/lib64/R/library/plotly/tests/figs/colorbar/plotly-colorbar-restrict.svg
/usr/lib64/R/library/plotly/tests/figs/colorbar/plotly-colorbar-z-expand.svg
/usr/lib64/R/library/plotly/tests/figs/colorbar/plotly-colorbar-z-restrict.svg
/usr/lib64/R/library/plotly/tests/figs/colorbar/plotly-colorbar.svg
/usr/lib64/R/library/plotly/tests/figs/colorscales/colorramp.svg
/usr/lib64/R/library/plotly/tests/figs/colorscales/contour-alpha.svg
/usr/lib64/R/library/plotly/tests/figs/colorscales/contour-colorscale.svg
/usr/lib64/R/library/plotly/tests/figs/colorscales/marker-colorscale.svg
/usr/lib64/R/library/plotly/tests/figs/colorscales/test-df.svg
/usr/lib64/R/library/plotly/tests/figs/colorscales/test-list-2.svg
/usr/lib64/R/library/plotly/tests/figs/colorscales/test-list-3.svg
/usr/lib64/R/library/plotly/tests/figs/colorscales/test-list.svg
/usr/lib64/R/library/plotly/tests/figs/colorscales/test-matrix.svg
/usr/lib64/R/library/plotly/tests/figs/contour/contour.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-axes/cookbook-axes-blank-minor-major.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-axes/cookbook-axes-blank-minor.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-axes/cookbook-axes-blank-x.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-axes/cookbook-axes-blank-y.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-axes/cookbook-axes-coord-ylim.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-axes/cookbook-axes-custom-formatter.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-axes/cookbook-axes-flevels.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-axes/cookbook-axes-fonts.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-axes/cookbook-axes-label-funs.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-axes/cookbook-axes-linear-axes.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-axes/cookbook-axes-log2-coord.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-axes/cookbook-axes-log2-labels.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-axes/cookbook-axes-log2-scale.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-axes/cookbook-axes-no-x-title.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-axes/cookbook-axes-scale-hide.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-axes/cookbook-axes-scale-name.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-axes/cookbook-axes-scale-y-log10-labels.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-axes/cookbook-axes-scale-y-log10.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-axes/cookbook-axes-ylim-hide.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-lines/cookbook-axes-bar-dodge-color-err4.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-lines/cookbook-axes-bar-dodge-color-error.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-lines/cookbook-axes-bar-dodge-color.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-lines/cookbook-axes-bar-error-diff.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-lines/cookbook-axes-bar-error-narrow.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-lines/cookbook-axes-bar-error-wide.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-lines/cookbook-axes-basic-bar.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-lines/cookbook-axes-basic-horizontal-line.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-lines/cookbook-axes-dashed-red-line.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-lines/cookbook-axes-scatter-basic.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-lines/cookbook-axes-scatter-facet-hline-vline.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-lines/cookbook-axes-scatter-facet-hline.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-lines/cookbook-axes-scatter-facet.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-lines/cookbook-axes-scatter-hline-vline.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-lines/cookbook-axes-scatter-hline.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-scatter/color.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-scatter/full-range.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-scatter/geom-jitter.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-scatter/hollow.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-scatter/jitter.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-scatter/loess.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-scatter/overlap.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-scatter/scale-color-hue.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-scatter/shape-manual.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-scatter/shape.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-scatter/smooth-lm-se-false.svg
/usr/lib64/R/library/plotly/tests/figs/cookbook-scatter/smooth-lm.svg
/usr/lib64/R/library/plotly/tests/figs/date/date-class-date.svg
/usr/lib64/R/library/plotly/tests/figs/date/date-irregular-time-series.svg
/usr/lib64/R/library/plotly/tests/figs/date/date-strings.svg
/usr/lib64/R/library/plotly/tests/figs/density2d/density2d.svg
/usr/lib64/R/library/plotly/tests/figs/density2d/density2dfill.svg
/usr/lib64/R/library/plotly/tests/figs/deps.txt
/usr/lib64/R/library/plotly/tests/figs/errorbar/errobar-flipped-aes.svg
/usr/lib64/R/library/plotly/tests/figs/errorbar/errobar-no-aes-y.svg
/usr/lib64/R/library/plotly/tests/figs/errorbar/errorbar-unique-groups.svg
/usr/lib64/R/library/plotly/tests/figs/errorbar/errorbar.svg
/usr/lib64/R/library/plotly/tests/figs/facets/3-panels.svg
/usr/lib64/R/library/plotly/tests/figs/facets/barley.svg
/usr/lib64/R/library/plotly/tests/figs/facets/facet-grid-free-x.svg
/usr/lib64/R/library/plotly/tests/figs/facets/facet-grid-free-y.svg
/usr/lib64/R/library/plotly/tests/figs/facets/facet-grid-free.svg
/usr/lib64/R/library/plotly/tests/figs/facets/facet-grid-labeller.svg
/usr/lib64/R/library/plotly/tests/figs/facets/facet-wrap-free-mult.svg
/usr/lib64/R/library/plotly/tests/figs/facets/facet-wrap-free-x.svg
/usr/lib64/R/library/plotly/tests/figs/facets/facet-wrap-free-y-2.svg
/usr/lib64/R/library/plotly/tests/figs/facets/facet-wrap-free-y.svg
/usr/lib64/R/library/plotly/tests/figs/facets/facet-wrap-free.svg
/usr/lib64/R/library/plotly/tests/figs/facets/facet-wrap-labeller.svg
/usr/lib64/R/library/plotly/tests/figs/facets/facet-wrap.svg
/usr/lib64/R/library/plotly/tests/figs/geom-col/col.svg
/usr/lib64/R/library/plotly/tests/figs/geom-errorbarh/errorbar-horizontal.svg
/usr/lib64/R/library/plotly/tests/figs/geom-jitter/jitter-basic.svg
/usr/lib64/R/library/plotly/tests/figs/geom-point/all-shapes.svg
/usr/lib64/R/library/plotly/tests/figs/geom-point/open-shapes.svg
/usr/lib64/R/library/plotly/tests/figs/geom-point/point-flip.svg
/usr/lib64/R/library/plotly/tests/figs/geom-point/point-size-alpha.svg
/usr/lib64/R/library/plotly/tests/figs/geom-point/point-size-alpha2.svg
/usr/lib64/R/library/plotly/tests/figs/geom-rect/rect-black.svg
/usr/lib64/R/library/plotly/tests/figs/geom-rect/rect-black4.svg
/usr/lib64/R/library/plotly/tests/figs/geom-rect/rect-color.svg
/usr/lib64/R/library/plotly/tests/figs/geom-rect/rect-fill-color.svg
/usr/lib64/R/library/plotly/tests/figs/geom-rect/rect-fill-hex-alpha.svg
/usr/lib64/R/library/plotly/tests/figs/geom-rect/rect-fill.svg
/usr/lib64/R/library/plotly/tests/figs/geom-sf/sf-aspect.svg
/usr/lib64/R/library/plotly/tests/figs/geom-sf/sf-axis-ticks.svg
/usr/lib64/R/library/plotly/tests/figs/geom-sf/sf-fill-text.svg
/usr/lib64/R/library/plotly/tests/figs/geom-sf/sf-geom-collection.svg
/usr/lib64/R/library/plotly/tests/figs/geom-sf/sf-points.svg
/usr/lib64/R/library/plotly/tests/figs/geom-sf/sf-theme-map.svg
/usr/lib64/R/library/plotly/tests/figs/geom-sf/sf.svg
/usr/lib64/R/library/plotly/tests/figs/ggplot-themes/theme-background.svg
/usr/lib64/R/library/plotly/tests/figs/ggplot-themes/theme-marker-default.svg
/usr/lib64/R/library/plotly/tests/figs/ggplot-themes/theme-panel-border-1.svg
/usr/lib64/R/library/plotly/tests/figs/ggplot-themes/theme-panel-border-2.svg
/usr/lib64/R/library/plotly/tests/figs/ggplot-themes/theme-ticks-and-grids.svg
/usr/lib64/R/library/plotly/tests/figs/ggplot-themes/theme-ticks-default.svg
/usr/lib64/R/library/plotly/tests/figs/ggplot-themes/theme-zeroline-default.svg
/usr/lib64/R/library/plotly/tests/figs/ggplot-ticks/continuous-x-missing.svg
/usr/lib64/R/library/plotly/tests/figs/ggplot-ticks/ticks-boxes-facet-grid.svg
/usr/lib64/R/library/plotly/tests/figs/ggplot-ticks/ticks-boxes-scales-free.svg
/usr/lib64/R/library/plotly/tests/figs/ggplot-ticks/ticks-boxes-space-free.svg
/usr/lib64/R/library/plotly/tests/figs/ggplot-ticks/ticks-boxes.svg
/usr/lib64/R/library/plotly/tests/figs/ggplot-ticks/ticks-breaks-less.svg
/usr/lib64/R/library/plotly/tests/figs/ggplot-ticks/ticks-breaks-more.svg
/usr/lib64/R/library/plotly/tests/figs/ggplot-ticks/ticks-breaks-nochange.svg
/usr/lib64/R/library/plotly/tests/figs/ggplot-ticks/ticks-evenly-spaced-ticks.svg
/usr/lib64/R/library/plotly/tests/figs/ggplot-ticks/ticks-flip-grid-free.svg
/usr/lib64/R/library/plotly/tests/figs/ggplot-ticks/ticks-flip-grid.svg
/usr/lib64/R/library/plotly/tests/figs/ggplot-ticks/ticks-flip.svg
/usr/lib64/R/library/plotly/tests/figs/ggplot-ticks/ticks-hide-ticks-labels.svg
/usr/lib64/R/library/plotly/tests/figs/ggplot-ticks/ticks-hide-ticks-lines-labels.svg
/usr/lib64/R/library/plotly/tests/figs/ggplot-ticks/ticks-limits-gap.svg
/usr/lib64/R/library/plotly/tests/figs/ggplot-ticks/ticks-limits-hide.svg
/usr/lib64/R/library/plotly/tests/figs/ggplot-ticks/ticks-line-breaks.svg
/usr/lib64/R/library/plotly/tests/figs/ggplot-ticks/ticks-scale-labels.svg
/usr/lib64/R/library/plotly/tests/figs/ggplot-ticks/ticks-uneven.svg
/usr/lib64/R/library/plotly/tests/figs/ggplot-ticks/ticks-ycontinuous-ranges.svg
/usr/lib64/R/library/plotly/tests/figs/ggplot-ticks/ticks-ylim-ranges.svg
/usr/lib64/R/library/plotly/tests/figs/ggplot-ticks/ticks-ylim-reversed-ranges.svg
/usr/lib64/R/library/plotly/tests/figs/ggplot-ticks/ticks-yreverse-limits-ranges.svg
/usr/lib64/R/library/plotly/tests/figs/ggplot-ticks/ticks-yreverse-ranges.svg
/usr/lib64/R/library/plotly/tests/figs/ggplot-ylim/ylim-one-trace.svg
/usr/lib64/R/library/plotly/tests/figs/heatmap/heatmap-discrete.svg
/usr/lib64/R/library/plotly/tests/figs/heatmap/heatmap-midpoint.svg
/usr/lib64/R/library/plotly/tests/figs/heatmap/heatmap.svg
/usr/lib64/R/library/plotly/tests/figs/hex/hex-basic.svg
/usr/lib64/R/library/plotly/tests/figs/hex/hex-bins.svg
/usr/lib64/R/library/plotly/tests/figs/hex/hex-binwidth.svg
/usr/lib64/R/library/plotly/tests/figs/histogram/histogram-counts.svg
/usr/lib64/R/library/plotly/tests/figs/histogram/histogram-date-bins.svg
/usr/lib64/R/library/plotly/tests/figs/histogram/histogram-dates.svg
/usr/lib64/R/library/plotly/tests/figs/histogram/histogram-density-binwidth.svg
/usr/lib64/R/library/plotly/tests/figs/histogram/histogram-density.svg
/usr/lib64/R/library/plotly/tests/figs/histogram/histogram-fill-factor-dodge.svg
/usr/lib64/R/library/plotly/tests/figs/histogram/histogram-fill-factor-facets.svg
/usr/lib64/R/library/plotly/tests/figs/histogram/histogram-fill-factor-identity.svg
/usr/lib64/R/library/plotly/tests/figs/histogram/histogram-fill-factor.svg
/usr/lib64/R/library/plotly/tests/figs/histogram/histogram-fill.svg
/usr/lib64/R/library/plotly/tests/figs/histogram/histogram-fixed-fill-color.svg
/usr/lib64/R/library/plotly/tests/figs/histogram/histogram-posixt-bins.svg
/usr/lib64/R/library/plotly/tests/figs/histogram/histogram-vline.svg
/usr/lib64/R/library/plotly/tests/figs/hline/hline-factor.svg
/usr/lib64/R/library/plotly/tests/figs/hline/hline-multiple.svg
/usr/lib64/R/library/plotly/tests/figs/hline/hline.svg
/usr/lib64/R/library/plotly/tests/figs/hline/split-hline-vline-abline.svg
/usr/lib64/R/library/plotly/tests/figs/image-trace/colormodel.svg
/usr/lib64/R/library/plotly/tests/figs/image-trace/raster-basic.svg
/usr/lib64/R/library/plotly/tests/figs/labels/factor-labels.svg
/usr/lib64/R/library/plotly/tests/figs/labels/labels-angles.svg
/usr/lib64/R/library/plotly/tests/figs/labels/labels-ggtitle.svg
/usr/lib64/R/library/plotly/tests/figs/labels/labels-scale-x-continuous-name.svg
/usr/lib64/R/library/plotly/tests/figs/labels/labels-ylab.svg
/usr/lib64/R/library/plotly/tests/figs/labels/labs-element-blank.svg
/usr/lib64/R/library/plotly/tests/figs/legends/legend-hide-legend.svg
/usr/lib64/R/library/plotly/tests/figs/legends/legend-hide.svg
/usr/lib64/R/library/plotly/tests/figs/legends/legend-many-legend-items.svg
/usr/lib64/R/library/plotly/tests/figs/legends/legend-one-entry.svg
/usr/lib64/R/library/plotly/tests/figs/legends/legend-very-long-legend-items.svg
/usr/lib64/R/library/plotly/tests/figs/legends/scatter-legend.svg
/usr/lib64/R/library/plotly/tests/figs/lines/line-milliseconds.svg
/usr/lib64/R/library/plotly/tests/figs/lines/linetype-colors.svg
/usr/lib64/R/library/plotly/tests/figs/lines/linetype-types.svg
/usr/lib64/R/library/plotly/tests/figs/maps/map-facet.svg
/usr/lib64/R/library/plotly/tests/figs/means-and-error-bars/error-rect-alpha.svg
/usr/lib64/R/library/plotly/tests/figs/means-and-error-bars/error-simple-line-point-crazy.svg
/usr/lib64/R/library/plotly/tests/figs/means-and-error-bars/error-simple-line-point.svg
/usr/lib64/R/library/plotly/tests/figs/means-and-error-bars/error-simple-line.svg
/usr/lib64/R/library/plotly/tests/figs/means-and-error-bars/error-simple.svg
/usr/lib64/R/library/plotly/tests/figs/path/path-colored-groups-stay-together.svg
/usr/lib64/R/library/plotly/tests/figs/path/path-colors.svg
/usr/lib64/R/library/plotly/tests/figs/path/path-colors2.svg
/usr/lib64/R/library/plotly/tests/figs/path/path-line-symbols.svg
/usr/lib64/R/library/plotly/tests/figs/path/path-lines-diff-from-paths.svg
/usr/lib64/R/library/plotly/tests/figs/plotly-color/plotly-color-bar-color-factor-custom.svg
/usr/lib64/R/library/plotly/tests/figs/plotly-color/plotly-color-box-color-stroke.svg
/usr/lib64/R/library/plotly/tests/figs/plotly-color/plotly-color-color-manual.svg
/usr/lib64/R/library/plotly/tests/figs/plotly-color/plotly-color-scatterplot-color-factor-custom.svg
/usr/lib64/R/library/plotly/tests/figs/plotly-color/plotly-color-scatterplot-color-factor-custom2.svg
/usr/lib64/R/library/plotly/tests/figs/plotly-color/plotly-color-scatterplot-color-factor.svg
/usr/lib64/R/library/plotly/tests/figs/plotly-color/plotly-color-scatterplot-color-numeric-custom.svg
/usr/lib64/R/library/plotly/tests/figs/plotly-color/plotly-color-scatterplot-color-numeric.svg
/usr/lib64/R/library/plotly/tests/figs/plotly-color/plotly-color-scatterplot-scatter3d-axes.svg
/usr/lib64/R/library/plotly/tests/figs/plotly-group/plotly-nas-connect.svg
/usr/lib64/R/library/plotly/tests/figs/plotly-group/plotly-nas-within-color.svg
/usr/lib64/R/library/plotly/tests/figs/plotly-group/plotly-nas-within-color2.svg
/usr/lib64/R/library/plotly/tests/figs/plotly-group/plotly-nas-within-group.svg
/usr/lib64/R/library/plotly/tests/figs/plotly-group/plotly-nas.svg
/usr/lib64/R/library/plotly/tests/figs/plotly-group/plotly-no-nas-for-irrelevant-group.svg
/usr/lib64/R/library/plotly/tests/figs/plotly-group/simple-scatter-marker-color-group.svg
/usr/lib64/R/library/plotly/tests/figs/plotly-linetype/plotly-linetype-alphabetical.svg
/usr/lib64/R/library/plotly/tests/figs/plotly-linetype/plotly-linetype-linetype.svg
/usr/lib64/R/library/plotly/tests/figs/plotly-linetype/plotly-linetype-linetype2.svg
/usr/lib64/R/library/plotly/tests/figs/plotly-linetype/plotly-linetype-linetype3.svg
/usr/lib64/R/library/plotly/tests/figs/plotly-linetype/plotly-linetype-manual.svg
/usr/lib64/R/library/plotly/tests/figs/plotly-linetype/plotly-linetype-ordering.svg
/usr/lib64/R/library/plotly/tests/figs/plotly-symbol/plotly-symbol-alphabetical.svg
/usr/lib64/R/library/plotly/tests/figs/plotly-symbol/plotly-symbol-logical.svg
/usr/lib64/R/library/plotly/tests/figs/plotly-symbol/plotly-symbol-ordering.svg
/usr/lib64/R/library/plotly/tests/figs/plotly-symbol/plotly-symbol-pch.svg
/usr/lib64/R/library/plotly/tests/figs/plotly-symbol/plotly-symbol-scatterplot-symbol.svg
/usr/lib64/R/library/plotly/tests/figs/plotly-symbol/plotly-symbol-scatterplot-symbol2.svg
/usr/lib64/R/library/plotly/tests/figs/plotly-symbol/plotly-symbol-symbol-manual.svg
/usr/lib64/R/library/plotly/tests/figs/plotly/errorbar-width.svg
/usr/lib64/R/library/plotly/tests/figs/plotly/layout-grid.svg
/usr/lib64/R/library/plotly/tests/figs/plotly/plotly-alpha-blending.svg
/usr/lib64/R/library/plotly/tests/figs/plotly/plotly-alpha-no-color.svg
/usr/lib64/R/library/plotly/tests/figs/plotly/plotly-bar-inference.svg
/usr/lib64/R/library/plotly/tests/figs/plotly/plotly-box-data-array.svg
/usr/lib64/R/library/plotly/tests/figs/plotly/plotly-character-axis.svg
/usr/lib64/R/library/plotly/tests/figs/plotly/plotly-factor-axis.svg
/usr/lib64/R/library/plotly/tests/figs/plotly/plotly-group-within-trace.svg
/usr/lib64/R/library/plotly/tests/figs/plotly/plotly-histogram-vert.svg
/usr/lib64/R/library/plotly/tests/figs/plotly/plotly-histogram.svg
/usr/lib64/R/library/plotly/tests/figs/plotly/plotly-inherit-false.svg
/usr/lib64/R/library/plotly/tests/figs/plotly/plotly-scatterplot.svg
/usr/lib64/R/library/plotly/tests/figs/plotly/plotly-time-series-summary.svg
/usr/lib64/R/library/plotly/tests/figs/polygon/polygon-aes-color.svg
/usr/lib64/R/library/plotly/tests/figs/polygon/polygon-aes-fill.svg
/usr/lib64/R/library/plotly/tests/figs/polygon/polygon-black.svg
/usr/lib64/R/library/plotly/tests/figs/polygon/polygon-color-aes-fill.svg
/usr/lib64/R/library/plotly/tests/figs/polygon/polygon-color-fill-aes-linetype.svg
/usr/lib64/R/library/plotly/tests/figs/polygon/polygon-color-fill-aes-size.svg
/usr/lib64/R/library/plotly/tests/figs/polygon/polygon-star-fill-color.svg
/usr/lib64/R/library/plotly/tests/figs/polygon/polygon-star-group-color.svg
/usr/lib64/R/library/plotly/tests/figs/polygon/polygon-star-group.svg
/usr/lib64/R/library/plotly/tests/figs/polygon/polygons-canada-borders.svg
/usr/lib64/R/library/plotly/tests/figs/probability-density/density-color.svg
/usr/lib64/R/library/plotly/tests/figs/probability-density/density-fill.svg
/usr/lib64/R/library/plotly/tests/figs/probability-density/density-histogram.svg
/usr/lib64/R/library/plotly/tests/figs/probability-density/density-simple.svg
/usr/lib64/R/library/plotly/tests/figs/probability-density/density-traces-order.svg
/usr/lib64/R/library/plotly/tests/figs/ribbon/ribbon-alpha.svg
/usr/lib64/R/library/plotly/tests/figs/ribbon/ribbon-colour.svg
/usr/lib64/R/library/plotly/tests/figs/ribbon/ribbon-fill.svg
/usr/lib64/R/library/plotly/tests/figs/ribbon/ribbon-group.svg
/usr/lib64/R/library/plotly/tests/figs/segment/segment-multiple-non-numeric.svg
/usr/lib64/R/library/plotly/tests/figs/segment/segment.svg
/usr/lib64/R/library/plotly/tests/figs/size/marker-size.svg
/usr/lib64/R/library/plotly/tests/figs/size/size-global-scaling.svg
/usr/lib64/R/library/plotly/tests/figs/size/size-is-a-vector.svg
/usr/lib64/R/library/plotly/tests/figs/size/sizemode.svg
/usr/lib64/R/library/plotly/tests/figs/smooth/smooth-basic.svg
/usr/lib64/R/library/plotly/tests/figs/smooth/smooth-colour.svg
/usr/lib64/R/library/plotly/tests/figs/smooth/smooth-facet.svg
/usr/lib64/R/library/plotly/tests/figs/smooth/smooth-fill2.svg
/usr/lib64/R/library/plotly/tests/figs/smooth/smooth-group.svg
/usr/lib64/R/library/plotly/tests/figs/smooth/smooth-se-false.svg
/usr/lib64/R/library/plotly/tests/figs/step/step-gg-hv.svg
/usr/lib64/R/library/plotly/tests/figs/step/step-gg-hvh.svg
/usr/lib64/R/library/plotly/tests/figs/step/step-gg-vh.svg
/usr/lib64/R/library/plotly/tests/figs/step/step-gg-vhv.svg
/usr/lib64/R/library/plotly/tests/figs/subplot/plotly-subplot-geo-cartesian.svg
/usr/lib64/R/library/plotly/tests/figs/subplot/plotly-subplot-ggmatrix.svg
/usr/lib64/R/library/plotly/tests/figs/subplot/plotly-subplot-group.svg
/usr/lib64/R/library/plotly/tests/figs/subplot/plotly-subplot-plot-list.svg
/usr/lib64/R/library/plotly/tests/figs/subplot/plotly-subplot-recursive.svg
/usr/lib64/R/library/plotly/tests/figs/subplot/plotly-subplot-shareboth.svg
/usr/lib64/R/library/plotly/tests/figs/subplot/plotly-subplot-sharex.svg
/usr/lib64/R/library/plotly/tests/figs/subplot/plotly-subplot-sharey.svg
/usr/lib64/R/library/plotly/tests/figs/subplot/plotly-subplot-simple.svg
/usr/lib64/R/library/plotly/tests/figs/subplot/plotly-subplot-simple2.svg
/usr/lib64/R/library/plotly/tests/figs/subplot/plotly-subplot-subplot-legendgroup.svg
/usr/lib64/R/library/plotly/tests/figs/subplot/plotly-subplot-width-height.svg
/usr/lib64/R/library/plotly/tests/figs/subplot/subplot-bump-axis-annotation-shared.svg
/usr/lib64/R/library/plotly/tests/figs/subplot/subplot-bump-axis-annotation-traces-shared.svg
/usr/lib64/R/library/plotly/tests/figs/subplot/subplot-bump-axis-annotation-traces.svg
/usr/lib64/R/library/plotly/tests/figs/subplot/subplot-bump-axis-annotation.svg
/usr/lib64/R/library/plotly/tests/figs/subplot/subplot-bump-axis-image.svg
/usr/lib64/R/library/plotly/tests/figs/subplot/subplot-bump-axis-shape-shared.svg
/usr/lib64/R/library/plotly/tests/figs/subplot/subplot-bump-axis-shape.svg
/usr/lib64/R/library/plotly/tests/figs/subplot/subplot-reposition-annotation.svg
/usr/lib64/R/library/plotly/tests/figs/subplot/subplot-reposition-image.svg
/usr/lib64/R/library/plotly/tests/figs/subplot/subplot-reposition-shape-fixed.svg
/usr/lib64/R/library/plotly/tests/figs/subplot/subplot-reposition-shape.svg
/usr/lib64/R/library/plotly/tests/figs/sunburst/sunburst.svg
/usr/lib64/R/library/plotly/tests/figs/text/text-colour.svg
/usr/lib64/R/library/plotly/tests/figs/text/text.svg
/usr/lib64/R/library/plotly/tests/figs/thematic/thematic-geom-and-theme-defaults.svg
/usr/lib64/R/library/plotly/tests/figs/thematic/thematic-qualitative.svg
/usr/lib64/R/library/plotly/tests/figs/thematic/thematic-sequential.svg
/usr/lib64/R/library/plotly/tests/figs/tooltip/group-lines-hovertext.svg
/usr/lib64/R/library/plotly/tests/figs/tooltip/heatmap-discrete-tooltip.svg
/usr/lib64/R/library/plotly/tests/figs/tooltip/hovertext-display.svg
/usr/lib64/R/library/plotly/tests/figs/tooltip/tooltip-date.svg
/usr/lib64/R/library/plotly/tests/figs/tooltip/tooltip-datetime.svg
/usr/lib64/R/library/plotly/tests/figs/treemap/advanced.svg
/usr/lib64/R/library/plotly/tests/figs/treemap/basic.svg
/usr/lib64/R/library/plotly/tests/figs/violin/violin-aes.svg
/usr/lib64/R/library/plotly/tests/figs/violin/violin.svg
/usr/lib64/R/library/plotly/tests/figs/vline/vline-multiple.svg
/usr/lib64/R/library/plotly/tests/figs/vline/vline.svg
/usr/lib64/R/library/plotly/tests/figs/waterfall/waterfall-simple.svg
/usr/lib64/R/library/plotly/tests/testthat.R
/usr/lib64/R/library/plotly/tests/testthat/Rplots.pdf
/usr/lib64/R/library/plotly/tests/testthat/helper-skip.R
/usr/lib64/R/library/plotly/tests/testthat/helper-vdiffr.R
/usr/lib64/R/library/plotly/tests/testthat/test-animate-highlight.R
/usr/lib64/R/library/plotly/tests/testthat/test-api.R
/usr/lib64/R/library/plotly/tests/testthat/test-cookbook-axes.R
/usr/lib64/R/library/plotly/tests/testthat/test-cookbook-lines.R
/usr/lib64/R/library/plotly/tests/testthat/test-cookbook-scatterplots.R
/usr/lib64/R/library/plotly/tests/testthat/test-facet-axis.R
/usr/lib64/R/library/plotly/tests/testthat/test-geom-errorbar-flipped-aes.R
/usr/lib64/R/library/plotly/tests/testthat/test-geom-errorbar-issue-1751.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-abline.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-annotation_.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-area.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-bar.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-blank.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-boxplot.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-col.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-contour.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-coord-fixed.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-crossbar.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-date.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-density.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-density2d.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-device.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-dynamicTicks.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-errorbar-horizontal.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-errorbar.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-facets.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-ggplotly.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-heatmap.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-hex.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-histogram.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-hline.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-jitter.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-labels.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-legend.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-lines.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-map.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-path.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-point.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-polygons.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-quantile.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-rect.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-resize.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-ribbon.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-rug.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-segment.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-sf.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-size.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-smooth.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-spoke.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-step.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-text.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-theme.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-ticks.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-tooltip.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-violin.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-vline.R
/usr/lib64/R/library/plotly/tests/testthat/test-ggplot-ylim.R
/usr/lib64/R/library/plotly/tests/testthat/test-group2NA.R
/usr/lib64/R/library/plotly/tests/testthat/test-mean-error-bars.R
/usr/lib64/R/library/plotly/tests/testthat/test-plotly-color.R
/usr/lib64/R/library/plotly/tests/testthat/test-plotly-colorbar.R
/usr/lib64/R/library/plotly/tests/testthat/test-plotly-colorscale.R
/usr/lib64/R/library/plotly/tests/testthat/test-plotly-customdata.R
/usr/lib64/R/library/plotly/tests/testthat/test-plotly-data.R
/usr/lib64/R/library/plotly/tests/testthat/test-plotly-filename.R
/usr/lib64/R/library/plotly/tests/testthat/test-plotly-getfigure.R
/usr/lib64/R/library/plotly/tests/testthat/test-plotly-group.R
/usr/lib64/R/library/plotly/tests/testthat/test-plotly-image-trace.R
/usr/lib64/R/library/plotly/tests/testthat/test-plotly-internals.R
/usr/lib64/R/library/plotly/tests/testthat/test-plotly-isosurface.R
/usr/lib64/R/library/plotly/tests/testthat/test-plotly-linetype.R
/usr/lib64/R/library/plotly/tests/testthat/test-plotly-name.R
/usr/lib64/R/library/plotly/tests/testthat/test-plotly-partial-bundles.R
/usr/lib64/R/library/plotly/tests/testthat/test-plotly-pie.R
/usr/lib64/R/library/plotly/tests/testthat/test-plotly-sf.R
/usr/lib64/R/library/plotly/tests/testthat/test-plotly-shiny.R
/usr/lib64/R/library/plotly/tests/testthat/test-plotly-size.R
/usr/lib64/R/library/plotly/tests/testthat/test-plotly-splom.R
/usr/lib64/R/library/plotly/tests/testthat/test-plotly-subplot.R
/usr/lib64/R/library/plotly/tests/testthat/test-plotly-sunburst.R
/usr/lib64/R/library/plotly/tests/testthat/test-plotly-symbol.R
/usr/lib64/R/library/plotly/tests/testthat/test-plotly-treemaps.R
/usr/lib64/R/library/plotly/tests/testthat/test-plotly-waterfall.R
/usr/lib64/R/library/plotly/tests/testthat/test-plotly.R
/usr/lib64/R/library/plotly/tests/testthat/test-rotated-ticks.R
/usr/lib64/R/library/plotly/tests/testthat/test-style.R
/usr/lib64/R/library/plotly/tests/testthat/test-thematic.R
/usr/lib64/R/library/plotly/tests/testthat/test-ticktext-linebreaks.R
/usr/lib64/R/library/plotly/tests/testthat/test-toRGB.R
